name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ !contains(join("$COMMIT_MESSAGES", ', '), '#skip') }}
        run: echo "$COMMIT_MESSAGES"
