name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4     # checkouts the project source code from Git
      - uses: actions/setup-node@v4
        with:                        # pass the node version as a parameter to the setup-node action
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment on render
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        # this job will be dependent on the above env.CONDITION, note the `github.` prefix
        # which seem to be required while referencing the variable on the job level, but not the step level
        if: ${{ github.env.CONDITION == 'true' }}
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4     # checkouts the project source code from Git
      - uses: actions/setup-node@v4
        with:                        # pass the node version as a parameter to the setup-node action
          node-version: '20'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        if: ${{ github.env.CONDITION == 'true' }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DEFAULT_BUMP: 'patch'
      - name: A new version of Pekedex is deployed
        if: ${{ success() }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "Deploy Succeeded! Live version at https://full-stack-open-pokedex-n64h.onrender.com/"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build Failed
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "commit ${{ github.sha }} broke the build"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
